---
title: "ggplot2_2"
author: "Schwartz"
date: "11/2/2020"
output:
     html_document:
          toc: TRUE
          toc_depth: 4
          toc_float: true
          toc_collapsed: true
          theme: journal
          code_folding: show
---

<!--- Change font size for headers --->
<style>
h1.title {
  font-size: 30px;
}
h1 {
  font-size: 26px;
}
h2 {
  font-size: 22px;
}
h3 { 
  font-size: 18px;
}

</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE, 
                      fig.align = "center",
                      out.width = "80%")
```



                
# HW [GROUP ASSIGNMENT] 

*Each group member must contribute unique figures to the groups submission in order for all group members to get credit for this homework. If only some members of the group contribute figures in the submitted `.Rmd` file, those group members must additionally provide a supplemental explanation along with their submission as to why other students in their group have not contributed to this assignment.*

1. WHO Reporting Barplots (with uncertainty measures) separated by `WHO_region` using `facet_wrap`
    - Get the data from from [https://covid19.who.int/table](https://covid19.who.int/table)
        - The file should likely be named "WHO-COVID-19-global-data.csv"
    - Extend the lecture code with the `facet` feature from the last lecture
        - `facet_wrap(~ WHO_region, nrow=2, scale="free")`
    - to examine mortality rate
        - `mutate(rate = Cumulative_deaths/Cumulative_cases)`
    - and it's "theoretical" uncertainty
        - `mutate(SE = sqrt(rate*(1-rate)/Cumulative_cases))`
    - separated out by `WHO_region` (with, say, 5-10 countries per region)
- ***Each student in the group will choose different countries so all submitted plots are unique***

2. Infection Model Bar plots for the ICL and IHME methodologies
    - Get the data from [https://data.worldbank.org/indicator/SP.POP.TOTL](https://data.worldbank.org/indicator/SP.POP.TOTL) and [https://ourworldindata.org/covid-models](https://ourworldindata.org/covid-models)
        - For me, the former was called `API_SP/API_SP.POP.TOTL_DS2_en_csv_v2_1593924.csv`
        - while the latter were named
            - `daily-new-estimated-covid-19-infections-ihme-model.csv`
            - `daily-new-estimated-covid-19-infections-icl-model.csv`
        - Make plots of the country infection rates per 1000 residents 
            - ```mutate(ICL_mean_per1k = 1000*ICL_mean/`2019_pop`)```
        - including the uncertainties provided by the models, e.g., using
          - `mutate(ICL_upper_per1k = 1000*ICL_upper/`2019_pop`)`
          - `geom_errorbar(aes(xmin=ICL_mean_per1k-ICL_lower_per1k, xmax=ICL_mean_per1k+ICL_upper_per1k), width=.2)`
        - Again separated out by `WHO_region` (with, say, 5-10 countries per region)
            - `facet_wrap(~ WHO_region, nrow=2, scale="free")`
- ***Again, each student in the group will choose different countries so all submitted plots are unique***        
        
3. Use any of the above data to create a scatterplots or 2d density plots
    - which provides a representation of the COVID situation that you find interesting, noteworthy, or compelling
    - Code for scatter plots or 2d density plots is available in `ggplot2.Rmd` (*Class 6*)
- ***Each student in the group must create a distinct plot with a distinct focus***

4. +1 extra credit if ALL parts in C7.HW1 above are redone
    - in addition to the original assignment
    - at the same level of high quality as the original assignment
    - and by all members of the group each with their own data sets

# Resources

## Code 

### Online Textbooks 

- [R4DS -- Data Manipulation](https://r4ds.had.co.nz/transform.html)
- [R4DS -- Data Joining](https://r4ds.had.co.nz/relational-data.html)
- [STHDA -- error bars](http://www.sthda.com/english/wiki/ggplot2-error-bars-quick-start-guide-r-software-and-data-visualization)
- [R Cookbook -- error bars](http://www.cookbook-r.com/Graphs/Plotting_means_and_error_bars_(ggplot2))

### One-Off Answers

[Group by aggregation](https://stackoverflow.com/questions/41673414/r-aggregate-sum-totals-for-grouped-data-using-dplyr)
[Replace NA's](https://stackoverflow.com/questions/45576805/how-to-replace-all-na-in-a-dataframe-using-tidyrreplace-na)

### Manual Pages

- [geom_col](https://ggplot2.tidyverse.org/reference/geom_bar.html)


## Data

### Focus for Class

- [TIME article on Sweden](https://time.com/5899432/sweden-coronovirus-disaster/)
    - [TIME covid data presentation](https://time.com/5800901/coronavirus-map/)
- [John Hopkins](https://coronavirus.jhu.edu/map.html)
    - [John Hopkins Data Repository](https://github.com/CSSEGISandData/COVID-19/blob/master/README.md)
- [WHO Covid Data](https://covid19.who.int/table)
- [Covid Infection Estimation](https://ourworldindata.org/covid-models)
- [Would Bank Country Populations](https://data.worldbank.org/indicator/SP.POP.TOTL)

### Others from Class

- [www.worldometers.info coronavirus](https://www.worldometers.info/coronavirus/#countriese)
- [Statistical Rate Calculation](https://stattrek.com/estimation/standard-error.aspx)
- [Tom McClintock (R-Calif) Covid Claiims](https://www.capradio.org/articles/2020/05/05/tom-mcclintock-claimed-the-flu-killed-80000-americans-last-year-heres-why-thats-misleading/)
    - [Initial CDC Estimates](https://www.statnews.com/2018/09/26/cdc-us-flu-deaths-winter/)
    - [Updated CDC Estimates](https://www.cdc.gov/flu/about/burden-averted/2017-2018.htm)

### Generally

- [kaggle](https://www.kaggle.com/) 
- [seaborn](https://github.com/mwaskom/seaborn-data) 
- [CMU](http://lib.stat.cmu.edu/datasets/)  
- [Google Dataset Search](https://datasetsearch.research.google.com/)
- [data.world](https://data.world/search)
- [Data Portals](http://dataportals.org/)
- [UCIML Repo](http://archive.ics.uci.edu/ml/)
- [OpenDataMonitor](http://opendatamonitor.eu/)
- [Quandl](http://quandl.com/)
- [Wikipedia](https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research)
- [AWS data set](https://registry.opendata.aws/)
- [Quora.com](https://www.quora.com/Where-can-I-find-large-datasets-open-to-the-public)
- [The datasets subreddit](https://www.reddit.com/r/datasets)
- [Tycho](https://www.tycho.pitt.edu)
- [TFDS](https://www.tensorflow.org/datasets/catalog/overview)


