---
title: "ggplot2_1"
author: "Schwartz"
date: "9/19/2020"
output:
     html_document:
          toc: TRUE
          toc_depth: 4
          toc_float: true
          toc_collapsed: true
          theme: journal
          code_folding: show
---

<!--- Change font size for headers --->
<style>
h1.title {
  font-size: 34px;
}
h1 {
  font-size: 30px;
}
h2 {
  font-size: 26px;
}
h3 { 
  font-size: 22px;
}

</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE, 
                      fig.align = "center",
                      out.width = "80%")
```




# HW [Group Assignment]

*Each group member must contribute unique figures to the groups submission in order for all group members to get credit for this homework. If only some members of the group contribute figures in the submitted `.Rmd` file, those group members must additionally provide a supplemental explanation along with their submission as to why other students in their group have not contributed to this assignment.*

0. Review the 
   [ggplot2 documentation](https://r4ds.had.co.nz/data-visualisation.html)
   and related resources to your own satisfaction and as needed to complete the 
   exercise
1. Each students must find a data set they're interested in which lends itself to this assignment
    - The same data set may be used by different students so long as different parts of the data (i.e., different figures must be produced by each student)
    - As noted in the `DS3003_syllabus.html` (Class 1), `Pirates_Snakes.Rmd` and `Pirates_Snakes.ipynb` (Class 5), and in today's code (Class 6), some places where data can be found are
        - data analysis websites such as [kaggle](https://www.kaggle.com/) and 
          data repositories such as those provided by 
          [seaborn](https://github.com/mwaskom/seaborn-data) and
          [CMU](http://lib.stat.cmu.edu/datasets/). E.g., we've used the
          [penguins](https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv), 
          [strikes](http://lib.stat.cmu.edu/datasets/strikes), and
          [S&P](http://lib.stat.cmu.edu/datasets/spdc2693)) data sets
        - other similar resources, such as (in no particular order)
            - [Google Dataset Search](https://datasetsearch.research.google.com/)
            - [data.world](https://data.world/search)
            - [Data Portals](http://dataportals.org/)
            - [UCIML Repo](http://archive.ics.uci.edu/ml/)
            - [OpenDataMonitor](http://opendatamonitor.eu/)
            - [Quandl](http://quandl.com/)
            - [Wikipedia](https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research)
            - [AWS data set](https://registry.opendata.aws/)
            - [Quora.com](https://www.quora.com/Where-can-I-find-large-datasets-open-to-the-public)
            - [The datasets subreddit](https://www.reddit.com/r/datasets)
            - [Tycho](https://www.tycho.pitt.edu)
            - [TFDS](https://www.tensorflow.org/datasets/catalog/overview)
        
    - `data()` will show you data sets available in R
      - And you can load data as done in `Pirates_Snakes.Rmd` (Class 5), 
        e.g., `data("USArrests")`
        - **HOWEVER**, if you use a built-in data set, you can only get 80% of
          the maximum grade, with the following exception:
          - 20% of the assignment score is for "reading in" data from a `.csv` 
            or other tabular "non built-in" data source
          - ...so you you cat get full 100% by first saving an internal data set 
            to a `.csv` or other tabular data format and THEN reading it into R 
            (to get credit for the last 20%)
    
2. Use the `facets` feature of ggplot2
    - This aesthetic is demonstrated 
      [here](https://r4ds.had.co.nz/data-visualisation.html#facets)
3. Use both the `size` and `color` attributes in your graphic
    - These aesthetics are demonstrated in the "`hwy` versus `displ`" plots at [https://r4ds.had.co.nz/data-visualisation.html#aesthetic-mappings](https://r4ds.had.co.nz/data-visualisation.html#aesthetic-mappings):
        1. `ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy, color = class)) # (colored by 'class')`
        2. `ggplot(data = mpg) +  geom_point(mapping = aes(x = displ, y = hwy, size = class)) # (sized by 'class')`

5. For +1 point, use a "color blind friendly" color palette.
    - One example of how to do this with `scale_colour_manual(values=cbbPalette)` and
      `cbbPalette <- c("#009E73", "#CC79A7","#D55E00", "#000000","#56B4E9", "#F0E442", "#0072B2", "#E69F00")`
      is described [here](http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/#a-colorblind-friendly-palette)

Hint: you'll need 3 factor variables and two continuous variables to do this, though continuous variables can be discretized to produce factor level variables.



# ggplot2 (R) Resources

- Perhaps the best (most principled) plotting library around
- Here are the references/resources I've used to create the code in this file

## Canonical Resources
- [R4DS -- Data Visualization](https://r4ds.had.co.nz/data-visualisation.html)
- [tiidyverse -- learning ggplot2](https://ggplot2.tidyverse.org/#learning-ggplot2)
- [R4DS -- Graphics for Communication](https://r4ds.had.co.nz/graphics-for-communication.html)
  - [R4DS -- scales](https://r4ds.had.co.nz/graphics-for-communication.html#scales)
    - [R4DS -- rescaling](https://r4ds.had.co.nz/graphics-for-communication.html#replacing-a-scale)
- [R Cookbook](http://www.cookbook-r.com/Graphs/)
- [tidyverse -- ggplot2](https://ggplot2.tidyverse.org)

## Manual Pages
- [tidyverse readr](https://readr.tidyverse.org/reference/read_delim.html)
- [tidyverse str_replace](https://stringr.tidyverse.org/reference/str_replace.html)
- [tidyverse join](https://dplyr.tidyverse.org/reference/join.html)
- [tidyverse scale_viridis](https://ggplot2.tidyverse.org/reference/scale_viridis.html)

## Additional Resources
- [Proportional Ink](https://stackoverflow.com/questions/7714677/scatterplot-with-too-many-points)
- [Rotatinig Labels](https://community.rstudio.com/t/x-axis-labels-overlap-want-to-rotate-labels-45/63800)
- [Customizinig Ticks](http://www.sthda.com/english/wiki/ggplot2-axis-ticks-a-guide-to-customize-tick-marks-and-labels)

## Data Sets

### From Class

- [Kaggle 2016 Primaries](https://www.kaggle.com/benhamner/2016-us-election?select=primary_results.csv)
- [Kaggle County Facts](https://www.kaggle.com/benhamner/2016-us-election?select=county_facts.csv)

### Generally

- [kaggle](https://www.kaggle.com/)
- [seaborn](https://github.com/mwaskom/seaborn-data)
- [CMU](http://lib.stat.cmu.edu/datasets/)
- [Google Dataset Search](https://datasetsearch.research.google.com/)
- [data.world](https://data.world/search)
- [Data Portals](http://dataportals.org/)
- [UCIML Repo](http://archive.ics.uci.edu/ml/)
- [OpenDataMonitor](http://opendatamonitor.eu/)
- [Quandl](http://quandl.com/)
- [Wikipedia](https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research)
- [AWS data set](https://registry.opendata.aws/)
- [Quora.com](https://www.quora.com/Where-can-I-find-large-datasets-open-to-the-public)
- [The datasets subreddit](https://www.reddit.com/r/datasets)
- [Tycho](https://www.tycho.pitt.edu)
- [TFDS](https://www.tensorflow.org/datasets/catalog/overview)

